### ISSUE TITLE
equivalent to lodash map and flattenDeep?

### ISSUE THREAD

**Issue by tuananh** [dotmilk/mapMany#1]
this package looks like normal `map` and `flattenDeep`; the major difference with map is this one concat the result (hence the name `mapMany`?) instead of 1-1 map right?

also i think your version more performant than lodash `map` and `flattenDeep`.

```js
const { map, flattenDeep } = require('lodash')
let data = [{ foo: 'b', stuff: [1, 2] }, { foo: 'c', stuff: [3, 4] }]
let mapped = flattenDeep(
    map(data, function(item) {
        return item['stuff'].map(stuff => {
            let obj = {}
            obj['foo'] = item['foo']
            obj['thing'] = stuff
            return obj
        })
    })
)

console.log(mapped)
```

**Comment by dotmilk** [comment]
I primarily use this to take [{metainfo:, moremeta:, itemsMetaAppliesTo:[very huge array of objects] },.......]

and return an array of objects from itemsMetaAppliesTo with metainfo and moremeta applied to them. So yes, it is not a 1-1, it's 1 to many.  

I'm not sure about performance, as I don't use lodash or underscore, however I can say that this is fairly performant over the large data set I use it on.

A first glance it appears you could get the same result using those lodash methods, but again, I avoid libraries when possible.
